### ISSUE TITLE
Metadata API CORS error: Access-Control-Allow-Origin header not present on requested resouce

### ISSUE THREAD

**Issue by femans** [ipfs-search/dweb-search-frontend#204]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/625851/172144419-eaf18363-4d7c-4f42-95ae-cb83d50ec808.png">

There are 2 problems here, concerning the same issue:

- [ ] CORS errors from the server upon (some) requests to the metadata API (which ones?)
- [ ] uncaught error handling in the frontend code calling the metadata API.

To reproduce: 
from the main homepage of IPFS-search, type 'test' and enter. Check the console.

Expected: No errors
Witnessed behavior: 
* Errors (see above). 
* unclear (yet) if we miss certain metadata information or if it is for specific hits or file types only.

**Comment by dokterbob** [comment]
This problem occurs because:

1. There is no proper CORS header return for 500 responses from the metadata API. https://github.com/ipfs-search/ipfs-search-api/issues/35
2. Metadata requests are made for directories (e.g. `QmWn48k3sKsSNG4KNfuxHYhgotz4eVgtx73orkzjtQewQF`), which have no associated metadata and hence it should not be requested.

I would suggest for our current efforts we focus on resolving 2, while the next time anyone touches the metadata code we should resolve the CORS issue.
